version: 2.1

setup: true

orbs:
  unity: game-ci/unity@1.7.0

workflows:
  Activation:
    jobs:
      - unity/create-activation-file

      - unity/build:
          name: 'build-Windows64-il2cpp'
          step-name: 'Build StandaloneWindows64 il2cpp'
          unity-license-var-name: 'UNITY_ENCODED_LICENSE'
          unity-username-var-name: 'UNITY_USERNAME'
          unity-password-var-name: 'UNITY_PASSWORD'
          executor:
            name: 'unity/windows-2019'
            size: 'large'
            editor_version: 2022.3.16f1
            target_platform: 'windows-il2cpp'
          build-target: StandaloneWindows64
          project-path: './'
          compress: true
          context: unity